- name: Build Docker Image
  hosts: dockerservers
  remote_user: root
  tasks:
    - name: Build the Docker image
      docker_image:
        build:
          path: /var/lib/jenkins/workspace/neogym
        name: neogym
        tag: latest
