- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Build the Docker image
      docker_image:
        name: neogym                  # Name of your image
        tag: latest                   # Tag for the image
        build:
          path: /var/lib/jenkins/workspace/neogym  # Path to your Dockerfile
