- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Build the Docker image
      docker_image:
        name: neogym  # This is the name of your image.
        tag: latest    # This is the tag for the image.
