- name: Build Docker Image
  hosts: dockerservers
  gather_facts: no
  remote_user: root
  tasks:
    - name: Build the Docker image
      docker_image:
        name: neogym               # Image name
        tag: latest                # Image tag
        build:
          path: /var/lib/jenkins/workspace/neogym # Directory with Dockerfile
