- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Build the Docker image
      docker_image:
        name: neogym
        tag: latest
        path: /var/lib/jenkins/workspace/neogym/Dockerfile # Path where your Dockerfile is located

    - name: Creating the Container
      docker_container:
        name: neogym-container  # Docker container name
        image: neogym:latest    # Docker image name
        ports:
          - "80:80"             # Port mapping
        state: started
        restart: true
